<h2>Buildings</h2>
<table class="datatable">
    <tr>
        <th>Name</th>
        <th>Actions</th>
    </tr>
    <?php foreach ($buildings as $building) {?>
    <tr>
        <td><?php echo $building['name']?></td>
        <td class="actions">
            <a href="<?php echo $this->url('default', array('controller'=>'admin-building', 'action'=>'view')).'?id='.$building['id'];?>" class="small-icon view">&nbsp;</a>
            <a href="<?php echo $this->url('default', array('controller'=>'admin-building', 'action'=>'edit')).'?id='.$building['id'];?>" class="small-icon edit">&nbsp;</a>
            <a href="<?php echo $this->url('default', array('controller'=>'admin-building', 'action'=>'delete')).'?id='.$building['id'];?>" class="small-icon delete">&nbsp;</a>
        </td>
    </tr>
    <?php } ?>
</table>