<h2>Units</h2>
<table class="datatable">
    <tr>
        <th>Name</th>
        <th>Actions</th>
    </tr>
    <?php foreach ($units as $unit) {?>
    <tr>
        <td><?php echo $unit['name']?></td>
        <td class="actions">
            <a href="<?php echo $this->url('default', array('controller'=>'admin-unit', 'action'=>'view'));?>" class="small-icon view">&nbsp;</a>
            <a href="<?php echo $this->url('default', array('controller'=>'admin-unit', 'action'=>'edit'));?>" class="small-icon edit">&nbsp;</a>
            <a href="<?php echo $this->url('default', array('controller'=>'admin-unit', 'action'=>'delete'));?>" class="small-icon delete">&nbsp;</a>
        </td>
    </tr>
    <?php } ?>
</table>