<?php
$this->headTitle()->setSeparator(' - ')
        ->setAutoEscape(false);

$basePath = $this->basePath();
$this->headLink()->appendStylesheet($basePath . '/css/main.css');

$this->headLink(array(
    'rel' => 'shortcut icon',
    'type' => 'image/vnd.microsoft.icon',
    'href' => $basePath . '/images/favicon.ico',
));

//$this->headScript()->appendFile($basePath . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE9',));

echo $this->doctype();
?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Homepage') ?>

        <?php echo $this->headMeta() ?>

        <!-- Le styles -->
        <?php echo $this->headLink() ?>

        <style type="text/css">
            body {
                padding-top: 60px;
            }
        </style>

        <!-- Scripts -->
        <?php echo $this->headScript() ?>

    </head>

    <body>
        <div class="header">
            <div class="menu">
                <ul>
                    <li><a href="#">P1</a></li>
                </ul>
            </div>
        </div>
        <div class="container">
            <?php echo $this->content; ?>
        </div>
        <div class="footer">
            <div class="links"><a href="#">Something</a></div>
            <div class="copyright">&copy; Copyright 2011 - 2012 Kaur. All rights reserved.</div>
        </div>
    </body>
</html>
