<?php 
$this->headTitle('Users');
?>
<h2>User who play the game</h2>

<p class="page-description"></p>

<table class="data-table">
    <tr>
        <th>Name</th>
        <th>Last visit</th>
    </tr>
    <?php foreach ($users as $user) {?>
    <tr>
        <td><?php echo $user['first_name']?> <?php echo $user['last_name']?></td>
        <td><?php echo date("d.m.Y H:i:s", $user['last_visit'])?></td>
    </tr>
    <?php } ?>
</table>